name: efficientfsl
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - h5py=3.12.1=py39h5842655_1
  - hdf5=1.14.5=h2b7332f_2
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipython=8.15.0=py39h06a4308_0
  - jedi=0.19.2=py39h06a4308_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcurl=8.12.1=hc9e6f67_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - numpy-base=2.0.1=py39hb5e798b_1
  - openssl=3.0.16=h5eee18b_0
  - parso=0.8.4=py39h06a4308_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.0=py39h06a4308_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py39h06a4308_1
  - python=3.9.21=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - argcomplete==3.6.2
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - avalanche-lib==0.6.0
      - beautifulsoup4==4.13.3
      - boto==2.49.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - clarabel==0.10.0
      - click==8.1.8
      - clip==1.0
      - cmeel==0.57.1
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==43.0.3
      - cvxopt==1.3.2
      - cycler==0.12.1
      - daqp==0.6.0
      - dill==0.3.9
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - fasteners==0.19
      - filelock==3.13.1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - gast==0.6.0
      - gcs-oauth2-boto-plugin==3.2
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-apitools==0.5.32
      - google-auth==2.17.0
      - google-auth-httplib2==0.2.0
      - google-pasta==0.2.0
      - google-reauth==0.1.1
      - gputil==1.4.0
      - grpcio==1.71.0
      - gsutil==5.33
      - hf-xet==1.1.3
      - highspy==1.9.0
      - httplib2==0.20.4
      - huggingface-hub==0.32.6
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - jax==0.4.30
      - jaxlib==0.4.30
      - jaxopt==0.8.3
      - jinja2==3.1.4
      - joblib==1.4.2
      - keras==3.9.2
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - lightning-utilities==0.14.1
      - loguru==0.7.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.4.3
      - namex==0.0.8
      - networkx==3.2.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - oauth2client==4.1.3
      - opt-einsum==3.4.0
      - optree==0.15.0
      - osqp==0.6.7.post3
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.15.2.dev0
      - pillow==11.0.0
      - piqp==0.4.2
      - platformdirs==4.3.6
      - propcache==0.3.1
      - protobuf==5.29.3
      - proxsuite==0.7.2
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyopenssl==24.2.1
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytorchcv==0.0.67
      - pytz==2025.2
      - pyu2f==0.1.5
      - pyyaml==6.0.2
      - qdldl==0.1.7.post5
      - qpalm==1.2.5
      - qpax==0.0.9
      - qpsolvers==4.5.0
      - quadprog==0.1.13
      - regex==2024.11.6
      - requests==2.32.3
      - retry-decorator==1.1.1
      - rich==14.0.0
      - rsa==4.7.2
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - scs==3.2.7.post2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.6
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.0.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - timm==0.4.12
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchmetrics==1.6.3
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - transformers==4.52.4
      - triton==3.2.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - wandb==0.19.8
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yarl==1.19.0
      - zipp==3.21.0
